### PR TITLE
updated dependencies as of 9.10.19

### PR DESCRIPTION
**Pull request by hugo-a-garcia**
The dependencies updates happened when I did a 'npm link'. I ran 'npm audit fix' and it corrected all dependencies except:

1 vulnerability required manual review and could not be updated
1 package update for 42 vulnerabilities involved breaking changes

### CODE REVIEW

**Comment by davedoesdev** [comment]
@hugo-a-garcia thanks! I'll see if I can update them "by hand" and fix the npm audit

**Comment by hugo-a-garcia** [comment]
AHA! I the node issue might explain why it is not possible to run a loop in a worker thread???

**Comment by davedoesdev** [comment]
Possibly, I'll add a test and try it out

**Comment by davedoesdev** [comment]
@hugo-a-garcia thanks, appreciate it. Fixed in https://github.com/davedoesdev/shared-memory-disruptor/commit/887d5ec4b2533d6b98e057d22a4e5b04be44d4f7

**Pull request closed without merging**
